Add portaudio v19.7.0
bincrafters/community pull request #1377
Opened 2021-04-07 14:02 UTC by akemimadoka

## Description
Add portaudio v19.7.0

This version fixed bug https://github.com/PortAudio/portaudio/issues/395, this bug makes macOS Big Sur unable to open audio device

## Related Issue

## Motivation and Context

## How Has This Been Tested?

2021-04-07 15:00 UTC, Croydon requested changes

2021-04-07 15:00 UTC, Croydon commented on recipes/portaudio/all/conanfile.py
> +        cmake.install()
Similar question, just to make sure: CMake is now installing all relevant files on all platforms?

2021-04-08 04:26 UTC, akemimadoka commented on recipes/portaudio/all/conanfile.py
> -        "cpp_bindings": [True, False],
cpp_bindings seems not supported in CMake for now(https://github.com/PortAudio/portaudio/issues/539), so I removed it. if CMake is not good enough, I will change the recipe to use Autotools and add it back.

2021-04-08 04:59 UTC, akemimadoka commented
I tested the recipe in Windows 7, Ubuntu 20.04, and macOS Big Sur, it seems CMake is working well but lacks the support for cpp_bindings. Would it be better to change the recipe back and use Autotools?

2021-04-09 07:09 UTC, Croydon commented
I don't know, but I assume there was a reason for doing it like that in the first place. What was your motivation to change it to CMake-only?

2021-04-09 15:27 UTC, akemimadoka commented
In https://github.com/PortAudio/portaudio/pull/434, they seemed to reach a consensus that they would consider removing support for other build systems, so I think making this recipe CMake-only is helpful for compatibility with later versions

2021-08-18 07:52 UTC, closed without merging